### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by CodeATA** [vusec/deltapointers#1]
Hi, I'm having some difficulties in building the Delta Pointer project.  
I first tried to get code according to the README, but got a "Permission denied (publickey)" error when executing `git submodule`. So I directly cloned the [instrumentation-infra](https://github.com/vusec/instrumentation-infra) repository and rewound to version e180447.
Then I executed the building command
`$ ./setup.py run --build deltatags-test clang-lto deltatags`
and got the following error messages when fetching libelf-0.7.0

> 15:41:21 [INFO] fetching libelf-0.7.0
15:41:23 [CRITICAL] unkown error
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/home/usr1992/deltapointers/infra/infra/setup.py", line 734, in _run_command
    self._run_run()
  File "/home/usr1992/deltapointers/infra/infra/setup.py", line 668, in _run_run
    self._run_build()
  File "/home/usr1992/deltapointers/infra/infra/setup.py", line 535, in _run_build
    self._fetch_package(package, self.args.force_rebuild_deps)
  File "/home/usr1992/deltapointers/infra/infra/setup.py", line 444, in _fetch_package
    package.fetch(self.ctx, *args)
  File "/home/usr1992/deltapointers/infra/infra/packages/prelink/__init__.py", line 21, in fetch
    download(ctx, 'http://www.mr511.de/software/' + tarname)
  File "/home/usr1992/deltapointers/infra/infra/util.py", line 237, in download
    urlretrieve(url, outfile)
  File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

How can I fix this?

**Comment by taddeus** [comment]
Hi there!

I have seen the git permissions error before when cloning the repo through HTTPS. Did you add your pubkey to your github account? That might fix the issue.

The build error seems to be caused by the libelf website being down. I hope that is only temporary. libelf is only being downloaded to be able to build prelink. As a quick workaround, you can try installing prelink manually using your package manager and disabling it as a dependency in infra/infra/packages/libshrink.py by commenting line 37: "yield Prelink('209')". Let me know if that works.

**Comment by CodeATA** [comment]
I installed prelink manually and have successfully run the test. Thanks for helping!

**Comment by taddeus** [comment]
Happy to help, and glad to hear it worked!
